name: Coverage
on:
    push:
        branches:
            - main
    pull_request:
        branches: ["main"]
        types: [opened, synchronize, reopened]
    workflow_dispatch:
jobs:
    test_coverage:
        name: Publish Storybook (Mobile) test coverage to SonarCloud
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
            - run: npm install
            - run: npm run test-storybook:coverage:ci --workspace=mobile
            - run: npm run coverage-report --workspace=mobile
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
